apiVersion: v1
name: athens-proxy
version: 0.5.2
appVersion: 0.11.1
description: The proxy server for Go modules
icon: https://raw.githubusercontent.com/gomods/athens/main/docs/static/banner.png
keywords:
- Golang
- Package Management
- Goproxy
home: https://github.com/gomods/athens
sources:
maintainers:
- name: rimusz
  email: rmocius@gmail.com
- name: arschles
  email: aaron@ecomaz.net
engine: gotpl
