services:
  - docker
language: go
install: false
go:
  - "1.11.x"
env:
  global:
    - PATH=${PATH}:./bin
    - GO_ENV=test
    - MINIO_ACCESS_KEY=minio
    - MINIO_SECRET_KEY=minio123
    - CODE_COV=1
    - ATHENS_DIR=${GOPATH}/src/github.com/gomods/athens
    - REGISTRY=gomods/
    - GORELEASER_ON=1
  matrix:
    # remove this after Go1.12 ships
    - GO111MODULE=auto
    - GO111MODULE=on

before_script:
  - mkdir -p $ATHENS_DIR && rsync -azr . $ATHENS_DIR && cd $ATHENS_DIR
  - make setup-dev-env
  - wget "https://dl.minio.io/server/minio/release/linux-amd64/minio"
  - chmod +x minio && nohup ./minio server . &

script:
  - make verify test-unit test-e2e

after_success:
  - if [ "${CODE_COV}" == "1" ]; then
      curl -s https://codecov.io/bash -o codecov && bash codecov -X fix;
    else
      echo codecov not enabled;
    fi

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: make docker-push
    on:
      repo: gomods/athens
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      repo: gomods/athens
      tags: true 
      condition: $GORELEASER_ON = 1
      condition: $GO111MODULE = on