# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'vs2017-win2016'

variables:
  GOBIN:  '$(GOPATH)\bin' # Go binaries path
  GOPATH: '$(system.defaultWorkingDirectory)\gopath' # Go workspace path
  GO111MODULE: 'on'
  modulePath: '$(GOPATH)\src\github.com\$(build.repository.name)' # Path to the module's code

steps:
- powershell: |
    mkdir "$env:GOBIN"
    mkdir "$env:GOPATH\pkg"
    mkdir "$env:modulePath"
    robocopy "$env:system_defaultWorkingDirectory\" "$env:modulePath\" /E /Z /ZB /R:5 /W:5 /TBD /NP /V /XD "$env:GOPATH"
    exit ($LastExitCode -band 24)
  displayName: 'Set up the Go workspace'

- powershell: |
    docker-compose -f docker-compose.win.yml -p athensdev up -d mongo
    Invoke-WebRequest -Uri "https://dl.minio.io/server/minio/release/windows-amd64/minio.exe" -OutFile "minio.exe"
    Start-Process -NoNewWindow minio.exe server --address ":9001" .
    go build -mod=vendor ./cmd/proxy
    go test -mod=vendor -race ./...
  env:
    ATHENS_MINIO_ENDPOINT: "127.0.0.1:9001"
    ATHENS_MONGO_STORAGE_URL: "mongodb://127.0.0.1:27017"
  workingDirectory: '$(modulePath)'
  displayName: 'Build & test proxy'
