name: Release canary and commit tags
on:
  push:
    branches:
      - main
jobs:
  docker-push-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push canary tag
        uses: docker/build-push-action@v4
        with:
          file: cmd/proxy/Dockerfile
          build-args: VERSION=${{github.sha}}
          tags: gomods/athens:canary
      - name: Build and push commit tag
        uses: docker/build-push-action@v4
        with:
          file: cmd/proxy/Dockerfile
          build-args: VERSION=${{github.sha}}
          tags: gomods/athens-dev:${GITHUB_SHA::7}